server:
  port: 8888
  servlet:
    session:
      timeout: -1

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: app
  profiles:
    active: dev, prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/air_test_demo
    username: root
    password: root
    hikari:
      leak-detection-threshold: 60000
      maximum-pool-size: 20
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        jdbc:
          time_zone: Europe/Moscow

  #email settings

  mail:
    host: smtp.gmail.com
    port: 587
    username: s77airlines@gmail.com
    password: lmconnwrrbbnrtge
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          auth: true

#logging:

